(() => {
  const ru = {
    "nav.status": "Available for Q3",
    "nav.home": "Главная",
    "nav.product": "Продукт",
    "nav.tech": "Технологии",
    "nav.app": "Применение",
    "nav.work": "Работы",
    "nav.about": "Обо мне",
    "nav.services": "Услуги",
    "nav.process": "Процесс",
    "nav.reviews": "Отзывы",
    "nav.cta": "Давайте поговорим",
    "nav.contact": "Контакт",
    "nav.menu": "Открыть меню",
    "nav.menuClose": "Закрыть меню",
    "nav.aria": "Основная навигация",
    "nav.lang": "Язык",
    "nav.homeBack": "← На главную",
    "nav.prevCase": "Предыдущий кейс",
    "nav.nextCase": "Следующий кейс",
    "cursor.case": "Кейс",
    "hero.kicker": "дизайнер интерфейсов",
    "hero.display": "Создание осмысленных цифровых опытов.",
    "hero.lede": "Я решаю сложные задачи продуктов с помощью тщательного исследования пользователей и минималистичных дизайнерских решений. Создание систем, которые соединяют людей и технологии.",
    "hero.ctaCases": "Посмотреть избранное",
    "hero.ctaStory": "Прочитать мою историю",
    "hero.alt": "Визуальный стиль портфолио — тёплый песочный мудборд",
    "about.display": "Форма следует за ощущением, создана для масштаба.",
    "about.side": "Соединяя строгие стратегические бизнес-цели с гибким, органическим интерактивным поведением человека.",
    "about.h3": "Дизайн с чистой сдержанностью для повышения рабочих процессов.",
    "about.p1": "Создаю понятные и удобные цифровые интерфейсы, трансформируя сложные технические задачи в интуитивные UI/UX решения. Я считаю, что отличная система дизайна — это не только визуальная документация, а масштабируемая платформа, которая создает культурную динамику внутри команд.",
    "about.p2": "Моя практика глубоко укоренена в строгом тестировании пользователей и чистой типографике. Убирая излишнюю структуру, мы делаем место для ясности и позволяем функциональной чистоте продукта проявиться.",
    "about.quoteBy": "Tetiana Zaichenko",
    "svc.display": "Услуги, ориентированные на жизненный цикл продукта.",
    "svc.side": "Комплексные интерактивные возможности — от валидации стратегии до финальной документации архитектуры системы.",
    "svc.1t": "Исследование UX",
    "svc.1p": "Глубокие воркшопы по открытию потребностей пользователей, непрерывные интервью, карты юзабилити и комплексная проверка поведения.",
    "svc.2t": "Дизайн интерфейса",
    "svc.2p": "Интерфейсы с точностью до пикселя, высокого качества и адаптивные, основанные на строгих формулах компоновки и высоко отполированных графических стандартах.",
    "svc.3t": "Прототипирование",
    "svc.3p": "Интерактивные поведенческие модели, идеально отражающие динамические потоки состояний, кастомные переходы и микроинтеракции с реальным ощущением.",
    "svc.4t": "Системы дизайна",
    "svc.4p": "Масштабируемая архитектура компонентов с токенизированными вариациями, тщательные протоколы передачи разработчикам и правила структурного управления.",
    "work.display": "Кейсы, построенные с точностью до пикселя.",
    "work.side": "Коллекция сложных цифровых решений, ориентированных на строгие цели продукта, интерактивную логику и масштабные фреймворки.",
    "tag.ux": "UX-аудит",
    "tag.health": "HealthTech",
    "tag.platform": "Платформа",
    "tag.web": "Веб-приложение",
    "tag.ed": "EdTech / GovTech",
    "work.role26": "2026 · Тим-лид дизайна",
    "work.role25": "2025 · Тим-лид дизайна",
    "work.micP": "Интеграция передовых биотехнологических решений в системы цифрового мониторинга. Оптимизация сбора биометрических данных пациентов для превентивной диагностики и персонализированной терапии.",
    "work.mjP": "MamaJoy — адаптивная Mobile-first экосистема и маркетплейс для беременных и молодых мам в Германии. Интуитивный UX, трекеры здоровья и заказ за 30 секунд.",
    "work.kfP": "Единая цифровая экосистема для жителей Кёльна: поиск, подбор и запись в секции, школы и кружки. Мультиязычность, сквозной поиск и централизованное бронирование.",
    "ops.display": "Современные Design Ops — все на карте.",
    "ops.side": "Универсальный набор инструментов для сложных мультиплатформенных продуктов — от интервью до кода в продакшене.",
    "ops.c1": "Основные дисциплины",
    "ops.c2": "Инструменты и технологии",
    "ops.c3": "Методологии",
    "ops.l1": "Дизайн интеракции",
    "ops.l2": "UX-аудит поведения",
    "ops.l3": "Масштабируемые системы дизайна",
    "ops.l4": "Информационная архитектура",
    "ops.l5": "Быстрое прототипирование в Framer",
    "ops.l6": "Исследование пользователей и аудит",
    "ops.t1": "Figma Enterprise",
    "ops.t2": "React / Next.js",
    "ops.t3": "Framer Motion",
    "ops.t4": "Principle",
    "ops.t5": "Tailwind CSS",
    "ops.t6": "GitHub Ecosystem",
    "ops.m1": "Процесс «Двойной бриллиант»",
    "ops.m2": "Непрерывное открытие",
    "ops.m3": "Agile Design Ops",
    "ops.m4": "Section 508 / WCAG",
    "ops.m5": "Количественные аудиты A/B",
    "proc.display": "Систематический процесс продукта.",
    "proc.side": "Как я двигаюсь от неясных проблем к готовым дизайнерским фреймворкам в производстве.",
    "proc.1t": "Открытие и определение объема",
    "proc.1p": "Картирование проблем продукта через глубокие интервью и согласование бизнес-метрик.",
    "proc.2t": "Интерактивные фреймворки",
    "proc.2p": "Итерация поведенческих вайрфреймов для механики навигации и правил системы.",
    "proc.3t": "Отполированные визуалы",
    "proc.3p": "Визуальный дизайн с микро-контентом и масштабируемыми токенами.",
    "proc.4t": "Передача и управление",
    "proc.4p": "Спецификации для разработки и непрерывный поведенческий аудит.",
    "quotes.display": "Что клиенты говорят об ",
    "quotes.side": "Тесное сотрудничество с растущими компаниями и корпоративными командами — чтобы прогресс продукта можно было проверить.",
    "quotes.q": "«Татьяна полностью трансформировала наш веб-интерфейс для сбора биометрических данных. Под ее руководством по UX/UI и front-end разработке стартап получил чистый, адаптивный код в VS Code и масштабируемую Figma-систему с ИИ-инструментами, что позволило нашей команде ускорить сдачу спринтов и безупречно внедрить Agile-процессы. Абсолютно системный мыслитель и проактивный специалист».",
    "quotes.role": "Chief Executive Officer · Industrial Biotechnologist Entrepreneur",
    "cta.kicker": "Давайте работать вместе",
    "cta.display": "У вас есть амбициозный<br>проект?",
    "cta.lede": "Сейчас я принимаю новые проекты по системам и визуальному дизайну. Если вы строите сложные инструменты для разработчиков, платформы здравоохранения или финтех-сети, давайте подготовим системный ответ.",
    "cta.alt": "Тёплая архитектурная арка из песочного камня",
    "foot.copy": "© 2025 Tetiana Zaichenko. Все права защищены.",
    "case.badge": "UX/UI Case Study",
    "case.role": "Роль",
    "case.time": "Сроки",
    "case.tools": "Инструменты",
    "case.plat": "Платформа",
    "case.roleVal": "Lead UX/UI Designer",
    "case.about": "О проекте",
    "case.pain": "Проблема и боли пользователей",
    "case.research": "Глубинное исследование",
    "case.personas": "Персонажи (User Personas)",
    "case.flow": "Путь пользователя (User Flow)",
    "case.lofi": "Лоу-фай прототипы и итерации",
    "case.id": "Айдентика и визуальный язык",
    "case.ui": "Финальный UI-дизайн",
    "case.ix": "Интерактивное взаимодействие с продукцией",
    "case.insights": "Ключевые инсайты",
    "case.st": "Статус:",
    "case.go": "Цели:",
    "case.pa": "Болевые точки:",
    "case.be": "Поведение на сайте:",
    "case.path": "Путь пользователя:",
    "case.needOn": "Что важно на сайте:",
    "case.needThem": "Что для них важно:",
    "case.pathSite": "Путь пользователя по сайту:",
    "case.colors": "Цветовые решения",
    "case.comps": "Компоненты интерфейса",
    "case.tested": "✓ Подтверждено пользовательским тестированием",
    "case.iter1": "Итерация 1",
    "case.iter2": "Итерация 2",
    "case.iter3": "Итерация 3",
    "case.statInt": "Глубинных интервью",
    "case.statSurvey": "Ответов на онлайн-опрос",
    "case.statComp": "Ключевых конкурента",
    "case.compH": "Анализ конкурентных решений",
    "mj.h": "MamaJoy — мобильное приложение онлайн-магазина, созданного для мам и их малышей до 2 лет.",
    "mj.lede": "Интуитивный мобильный сервис для беременных и родителей детей до 2 лет: подбор товаров, меньше когнитивной нагрузки, забота в ежедневной рутине.",
    "mj.timeVal": "3 месяца (2025)",
    "mj.toolsVal": "Figma, FigJam / Miro, VS Code",
    "mj.platVal": "iOS & Android",
    "kf.h": "Klubfinder — цифровая экосистема для академического сообщества",
    "kf.lede": "Веб-ресурс для школ и клубов Кёльна. Понятная архитектура для абитуриентов, учащихся и преподавателей.",
    "kf.timeVal": "1 месяц (2025)",
    "kf.platVal": "Web / Desktop & Mobile",
    "mic.h": "MicBioMate — ПЛАТФОРМА ДЛЯ БИОСИНТЕЗА ИНТАКТНОГО КЕРАТИНА",
    "mic.lede": "Разработка корпоративного веб-ресурса для биотехнологического стартапа. Проектирование понятной информационной архитектуры, объединяющей научные данные, описание технологий и разделы для партнеров. Акцент на инновационности, безопасности и удобстве доступа к сложной биотехнологической информации.",
    "mic.timeVal": "1,5 месяца (2026)",
    "mic.toolsVal": "Figma, FigJam / Miro, VS Code, Python",
    "mic.platVal": "Web / Desktop & Mobile",
  };

  const en = {
    "nav.status": "Available for Q3",
    "nav.home": "Home",
    "nav.product": "Product",
    "nav.tech": "Technologies",
    "nav.app": "Application",
    "nav.work": "Work",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.process": "Process",
    "nav.reviews": "Reviews",
    "nav.cta": "Let’s talk",
    "nav.contact": "Contact",
    "nav.menu": "Open menu",
    "nav.menuClose": "Close menu",
    "nav.aria": "Primary navigation",
    "nav.lang": "Language",
    "nav.homeBack": "← Back home",
    "nav.prevCase": "Previous case",
    "nav.nextCase": "Next case",
    "cursor.case": "Case",
    "hero.kicker": "interface designer",
    "hero.display": "Creating meaningful digital experiences.",
    "hero.lede": "I solve complex product problems through careful user research and minimal design. Building systems that connect people and technology.",
    "hero.ctaCases": "View selected work",
    "hero.ctaStory": "Read my story",
    "hero.alt": "Warm sand moodboard — portfolio visual language",
    "about.display": "Form follows feeling, built for scale.",
    "about.side": "Connecting strict business goals with flexible, organic human interaction.",
    "about.h3": "Quiet restraint in design, built to lift workflows.",
    "about.p1": "I create clear digital interfaces, turning technical problems into intuitive UI/UX. A great design system is a scalable platform — not only visual documentation.",
    "about.p2": "My practice is rooted in user testing and clean type. Removing extra structure makes room for clarity.",
    "about.quoteBy": "Tetiana Zaichenko",
    "svc.display": "Services across the product lifecycle.",
    "svc.side": "From strategy validation to final system documentation.",
    "svc.1t": "UX research",
    "svc.1p": "Discovery workshops, ongoing interviews, usability maps and behavioural checks.",
    "svc.2t": "Interface design",
    "svc.2p": "Pixel-accurate, high-quality responsive interfaces with strict layout rules.",
    "svc.3t": "Prototyping",
    "svc.3p": "Interactive models of state flows, custom transitions and micro-interactions.",
    "svc.4t": "Design systems",
    "svc.4p": "Scalable component architecture, tokenised variants and handoff protocols.",
    "work.display": "Cases built with pixel precision.",
    "work.side": "Complex digital products with strict goals, interaction logic and scalable frameworks.",
    "tag.ux": "UX audit",
    "tag.health": "HealthTech",
    "tag.platform": "Platform",
    "tag.web": "Web app",
    "tag.ed": "EdTech / GovTech",
    "work.role26": "2026 · Design team lead",
    "work.role25": "2025 · Design team lead",
    "work.micP": "Biotech monitoring and intact keratin. Optimising biometric data collection for preventive diagnostics.",
    "work.mjP": "MamaJoy is a mobile-first marketplace for pregnant women and new mothers in Germany — calm UX and a 30-second order.",
    "work.kfP": "One digital ecosystem for Cologne: search, book clubs, schools and courses. Multilingual, central booking.",
    "ops.display": "Modern Design Ops — all on the map.",
    "ops.side": "A toolkit for complex multi-platform products — from interview to production code.",
    "ops.c1": "Core disciplines",
    "ops.c2": "Tools & technology",
    "ops.c3": "Methods",
    "ops.l1": "Interaction design",
    "ops.l2": "Behavioural UX audit",
    "ops.l3": "Scalable design systems",
    "ops.l4": "Information architecture",
    "ops.l5": "Rapid prototyping in Framer",
    "ops.l6": "User research and audit",
    "ops.t1": "Figma Enterprise",
    "ops.t2": "React / Next.js",
    "ops.t3": "Framer Motion",
    "ops.t4": "Principle",
    "ops.t5": "Tailwind CSS",
    "ops.t6": "GitHub Ecosystem",
    "ops.m1": "Double Diamond",
    "ops.m2": "Continuous discovery",
    "ops.m3": "Agile Design Ops",
    "ops.m4": "Section 508 / WCAG",
    "ops.m5": "Quantitative A/B audits",
    "proc.display": "A systematic product process.",
    "proc.side": "From fuzzy problems to production-ready design frameworks.",
    "proc.1t": "Discover and scope",
    "proc.1p": "Map product problems through interviews and business metrics.",
    "proc.2t": "Interactive frameworks",
    "proc.2p": "Iterate behavioural wireframes for navigation and system rules.",
    "proc.3t": "Polished visuals",
    "proc.3p": "Visual design with microcopy and scalable tokens.",
    "proc.4t": "Handoff and governance",
    "proc.4p": "Dev specs and ongoing behavioural audits.",
    "quotes.display": "What clients say about ",
    "quotes.side": "Close work with scaling companies and corporate operations for measurable product progress.",
    "quotes.q": "“Tetiana fully transformed our biometric data web interface. With her UX/UI and front-end lead, the startup received clean responsive code and a scalable Figma system — sprints moved faster, Agile stuck. A systems thinker.”",
    "quotes.role": "Chief Executive Officer · Industrial Biotechnologist Entrepreneur",
    "cta.kicker": "Let’s work together",
    "cta.display": "Have an ambitious<br>project?",
    "cta.lede": "I am taking new system and visual design work. Complex tools, health platforms, fintech — let’s build a systemic answer.",
    "cta.alt": "Warm sandstone architectural arch",
    "foot.copy": "© 2025 Tetiana Zaichenko. All rights reserved.",
    "case.badge": "UX/UI Case Study",
    "case.role": "Role",
    "case.time": "Timeline",
    "case.tools": "Tools",
    "case.plat": "Platform",
    "case.roleVal": "Lead UX/UI Designer",
    "case.about": "About the project",
    "case.pain": "Problem and user pains",
    "case.research": "In-depth research",
    "case.personas": "Personas",
    "case.flow": "User flow",
    "case.lofi": "Low-fi prototypes and iterations",
    "case.id": "Identity and visual language",
    "case.ui": "Final UI design",
    "case.ix": "Interaction",
    "case.insights": "Key insights",
    "case.st": "Status:",
    "case.go": "Goals:",
    "case.pa": "Pains:",
    "case.be": "Behaviour:",
    "case.path": "Path:",
    "case.colors": "Colour",
    "case.comps": "Interface components",
    "case.tested": "✓ Confirmed in user testing",
    "case.iter1": "Iteration 1",
    "case.iter2": "Iteration 2",
    "case.iter3": "Iteration 3",
    "case.statInt": "In-depth interviews",
    "case.statSurvey": "Online survey responses",
    "case.statComp": "Key competitors",
    "case.compH": "Competitive analysis",
    "mj.h": "MamaJoy — a mobile shop for mothers and babies up to 2 years.",
    "mj.lede": "An intuitive mobile service for pregnant women and parents of children under two: less cognitive load, care in daily routine.",
    "mj.timeVal": "3 months (2025)",
    "mj.toolsVal": "Figma, FigJam / Miro, VS Code",
    "mj.platVal": "iOS & Android",
    "kf.h": "Klubfinder — a digital ecosystem for the academic community",
    "kf.lede": "A modern web resource for Cologne schools and clubs. Clear IA for applicants, students and teachers.",
    "kf.timeVal": "1 month (2025)",
    "kf.platVal": "Web / Desktop & Mobile",
    "mic.h": "MicBioMate — a platform for intact keratin biosynthesis",
    "mic.lede": "Corporate site for a biotech startup: science, technology and partner sections.",
    "mic.timeVal": "1.5 months (2026)",
    "mic.toolsVal": "Figma, FigJam / Miro, VS Code, Python",
    "mic.platVal": "Web / Desktop & Mobile",
  };

  const uk = {
    "nav.status": "Available for Q3",
    "nav.home": "Головна",
    "nav.product": "Продукт",
    "nav.tech": "Технології",
    "nav.app": "Застосування",
    "nav.work": "Роботи",
    "nav.about": "Про мене",
    "nav.services": "Послуги",
    "nav.process": "Процес",
    "nav.reviews": "Відгуки",
    "nav.cta": "Поговорімо",
    "nav.contact": "Контакт",
    "nav.menu": "Відкрити меню",
    "nav.menuClose": "Закрити меню",
    "nav.aria": "Основна навігація",
    "nav.lang": "Мова",
    "nav.homeBack": "← На головну",
    "nav.prevCase": "Попередній кейс",
    "nav.nextCase": "Наступний кейс",
    "cursor.case": "Кейс",
    "hero.kicker": "дизайнерка інтерфейсів",
    "hero.display": "Створюю осмислений цифровий досвід.",
    "hero.lede": "Розв’язую складні продуктові задачі через дослідження користувачів і стриманий дизайн. Створюю системи, які з’єднують людей і технології.",
    "hero.ctaCases": "Дивитися обране",
    "hero.ctaStory": "Прочитати мою історію",
    "hero.alt": "Візуальний стиль портфоліо — теплий піщаний мудборд",
    "about.display": "Форма йде за відчуттям і розрахована на масштаб.",
    "about.side": "Поєдную чіткі бізнес-цілі з гнучкою, живою взаємодією людини з продуктом.",
    "about.h3": "Стриманий дизайн, який підсилює робочі процеси.",
    "about.p1": "Роблю зрозумілі цифрові інтерфейси: складні технічні задачі стають інтуїтивним UI/UX. Добра дизайн-система — це не лише візуальна документація, а платформа, яка росте разом із командою.",
    "about.p2": "Практика тримається на тестах із користувачами й чистій типографіці. Прибираю зайву структуру — з’являється ясність, і продукт читається без шуму.",
    "about.quoteBy": "Tetiana Zaichenko",
    "svc.display": "Послуги на весь життєвий цикл продукту.",
    "svc.side": "Від перевірки стратегії до фінальної документації архітектури системи.",
    "svc.1t": "Дослідження UX",
    "svc.1p": "Воркшопи з відкриття потреб, регулярні інтерв’ю, карти юзабіліті та перевірка поведінки.",
    "svc.2t": "Дизайн інтерфейсу",
    "svc.2p": "Точні до пікселя адаптивні інтерфейси зі строгими правилами композиції та графіки.",
    "svc.3t": "Прототипування",
    "svc.3p": "Інтерактивні моделі станів, переходів і мікроанімацій, які відчуваються як живий продукт.",
    "svc.4t": "Дизайн-системи",
    "svc.4p": "Масштабована архітектура компонентів, токени варіантів і протоколи передачі розробці.",
    "work.display": "Кейси, зібрані з точністю до пікселя.",
    "work.side": "Складні цифрові рішення з чіткими цілями продукту, логікою взаємодії та системами, які можна масштабувати.",
    "tag.ux": "UX-аудит",
    "tag.health": "HealthTech",
    "tag.platform": "Платформа",
    "tag.web": "Вебзастосунок",
    "tag.ed": "EdTech / GovTech",
    "work.role26": "2026 · Тімлідка дизайну",
    "work.role25": "2025 · Тімлідка дизайну",
    "work.micP": "Біотех-моніторинг та інтактний кератин. Збір біометричних даних для профілактики й персональної терапії.",
    "work.mjP": "MamaJoy — mobile-first маркетплейс для вагітних і молодих мам у Німеччині. Спокійний UX і замовлення за 30 секунд.",
    "work.kfP": "Єдина цифрова екосистема для Кельна: пошук і запис у секції, школи та гуртки. Кілька мов і централізоване бронювання.",
    "ops.display": "Сучасні Design Ops — усе на карті.",
    "ops.side": "Набір інструментів для складних мультиплатформених продуктів — від інтерв’ю до коду в продакшені.",
    "ops.c1": "Основні дисципліни",
    "ops.c2": "Інструменти й технології",
    "ops.c3": "Методології",
    "ops.l1": "Дизайн взаємодії",
    "ops.l2": "UX-аудит поведінки",
    "ops.l3": "Масштабовані дизайн-системи",
    "ops.l4": "Інформаційна архітектура",
    "ops.l5": "Швидке прототипування у Framer",
    "ops.l6": "Дослідження користувачів і аудит",
    "ops.t1": "Figma Enterprise",
    "ops.t2": "React / Next.js",
    "ops.t3": "Framer Motion",
    "ops.t4": "Principle",
    "ops.t5": "Tailwind CSS",
    "ops.t6": "GitHub Ecosystem",
    "ops.m1": "Процес «Подвійний діамант»",
    "ops.m2": "Безперервне відкриття",
    "ops.m3": "Agile Design Ops",
    "ops.m4": "Section 508 / WCAG",
    "ops.m5": "Кількісні A/B-аудити",
    "proc.display": "Систематичний процес продукту.",
    "proc.side": "Як я переходжу від неясної задачі до готових дизайн-фреймворків у продакшені.",
    "proc.1t": "Відкриття й обсяг",
    "proc.1p": "Картую проблеми продукту через глибинні інтерв’ю та узгодження бізнес-метрик.",
    "proc.2t": "Інтерактивні фреймворки",
    "proc.2p": "Ітерації поведінкових вайрфреймів для навігації та правил системи.",
    "proc.3t": "Відшліфований візуал",
    "proc.3p": "Візуальний дизайн із мікротекстом і масштабованими токенами.",
    "proc.4t": "Передача й керування",
    "proc.4p": "Специфікації для розробки та постійний поведінковий аудит.",
    "quotes.display": "Що клієнти кажуть про ",
    "quotes.side": "Тісна співпраця з компаніями, що зростають, і корпоративними командами — щоб поступ продукту можна було виміряти.",
    "quotes.q": "«Тетяна повністю змінила наш вебінтерфейс для збору біометричних даних. Під її керівництвом з UX/UI і front-end стартап отримав чистий адаптивний код і масштабовану систему у Figma — спринти пішли швидше, Agile закріпився. Системне мислення і проактивність».",
    "quotes.role": "Chief Executive Officer · Industrial Biotechnologist Entrepreneur",
    "cta.kicker": "Працюймо разом",
    "cta.display": "Маєте амбітний<br>проєкт?",
    "cta.lede": "Зараз беру нові проєкти з систем і візуального дизайну. Складні інструменти, health-платформи, фінтех — давайте зберемо системну відповідь.",
    "cta.alt": "Тепла архітектурна арка з піщаного каменю",
    "foot.copy": "© 2025 Tetiana Zaichenko. Усі права захищено.",
    "case.badge": "UX/UI Case Study",
    "case.role": "Роль",
    "case.time": "Терміни",
    "case.tools": "Інструменти",
    "case.plat": "Платформа",
    "case.roleVal": "Lead UX/UI Designer",
    "case.about": "Про проєкт",
    "case.pain": "Проблема і болі користувачів",
    "case.research": "Глибинне дослідження",
    "case.personas": "Персони",
    "case.flow": "Шлях користувача",
    "case.lofi": "Lo-fi прототипи й ітерації",
    "case.id": "Айдентика і візуальна мова",
    "case.ui": "Фінальний UI-дизайн",
    "case.ix": "Інтерактивна взаємодія",
    "case.insights": "Ключові інсайти",
    "case.st": "Статус:",
    "case.go": "Цілі:",
    "case.pa": "Болі:",
    "case.be": "Поведінка:",
    "case.path": "Шлях:",
    "case.colors": "Колір",
    "case.comps": "Компоненти інтерфейсу",
    "case.tested": "✓ Підтверджено тестуванням з користувачами",
    "case.iter1": "Ітерація 1",
    "case.iter2": "Ітерація 2",
    "case.iter3": "Ітерація 3",
    "case.statInt": "Глибинних інтерв’ю",
    "case.statSurvey": "Відповідей на онлайн-опитування",
    "case.statComp": "Ключових конкурентів",
    "case.compH": "Аналіз конкурентних рішень",
    "mj.h": "MamaJoy — мобільний магазин для мам і малюків до 2 років.",
    "mj.lede": "Інтуїтивний мобільний сервіс для вагітних і батьків дітей до двох років: підбір товарів, менше когнітивного навантаження, турбота в щоденній рутині.",
    "mj.timeVal": "3 місяці (2025)",
    "mj.toolsVal": "Figma, FigJam / Miro, VS Code",
    "mj.platVal": "iOS & Android",
    "kf.h": "Klubfinder — цифрова екосистема для академічної спільноти",
    "kf.lede": "Вебресурс для шкіл і клубів Кельна. Зрозуміла архітектура для абітурієнтів, учнів і викладачів.",
    "kf.timeVal": "1 місяць (2025)",
    "kf.platVal": "Web / Desktop & Mobile",
    "mic.h": "MicBioMate — платформа біосинтезу інтактного кератину",
    "mic.lede": "Корпоративний сайт біотех-стартапу: наука, технології та розділи для партнерів.",
    "mic.timeVal": "1,5 місяця (2026)",
    "mic.toolsVal": "Figma, FigJam / Miro, VS Code, Python",
    "mic.platVal": "Web / Desktop & Mobile",
  };

  const de = {
    "nav.status": "Available for Q3",
    "nav.home": "Start",
    "nav.product": "Produkt",
    "nav.tech": "Technologien",
    "nav.app": "Anwendung",
    "nav.work": "Arbeit",
    "nav.about": "Über mich",
    "nav.services": "Leistungen",
    "nav.process": "Prozess",
    "nav.reviews": "Stimmen",
    "nav.cta": "Sprechen wir",
    "nav.contact": "Kontakt",
    "nav.menu": "Menü öffnen",
    "nav.menuClose": "Menü schließen",
    "nav.aria": "Hauptnavigation",
    "nav.lang": "Sprache",
    "nav.homeBack": "← Zur Startseite",
    "nav.prevCase": "Vorheriger Case",
    "nav.nextCase": "Nächster Case",
    "cursor.case": "Case",
    "hero.kicker": "Interface-Designerin",
    "hero.display": "Sinnvolle digitale Erlebnisse gestalten.",
    "hero.lede": "Ich löse komplexe Produktfragen mit Nutzerforschung und ruhigem Design. Systeme, die Menschen und Technik verbinden.",
    "hero.ctaCases": "Ausgewählte Arbeiten",
    "hero.ctaStory": "Meine Geschichte",
    "hero.alt": "Visuelle Sprache des Portfolios — warmes Sand-Moodboard",
    "about.display": "Form folgt dem Gefühl, gebaut für Wachstum.",
    "about.side": "Strenge Geschäftsziele und lebendige, menschliche Interaktion zusammenhalten.",
    "about.h3": "Ruhiges Design, das Workflows trägt.",
    "about.p1": "Ich gestalte klare Interfaces: technische Probleme werden zu intuitivem UI/UX. Ein gutes Designsystem ist eine Plattform für Teams — nicht nur Dokumentation.",
    "about.p2": "Meine Praxis steht auf Tests und klarer Typografie. Weniger Struktur, mehr Klarheit.",
    "about.quoteBy": "Tetiana Zaichenko",
    "svc.display": "Leistungen über den Produktlebenszyklus.",
    "svc.side": "Von der Strategievalidierung bis zur Systemdokumentation.",
    "svc.1t": "UX-Research",
    "svc.1p": "Discovery-Workshops, Interviews, Usability-Karten und Verhaltenschecks.",
    "svc.2t": "Interface-Design",
    "svc.2p": "Pixelgenaue, responsive Interfaces mit strengen Layoutregeln.",
    "svc.3t": "Prototyping",
    "svc.3p": "Interaktive Modelle von Zuständen, Übergängen und Mikrointeraktionen.",
    "svc.4t": "Designsysteme",
    "svc.4p": "Skalierbare Komponenten, Tokens und Handoff-Protokolle.",
    "work.display": "Cases mit Pixelgenauigkeit.",
    "work.side": "Komplexe digitale Produkte mit klaren Zielen, Interaktionslogik und skalierbaren Frameworks.",
    "tag.ux": "UX-Audit",
    "tag.health": "HealthTech",
    "tag.platform": "Plattform",
    "tag.web": "Web-App",
    "tag.ed": "EdTech / GovTech",
    "work.role26": "2026 · Design-Teamlead",
    "work.role25": "2025 · Design-Teamlead",
    "work.micP": "Biotech-Monitoring und intaktes Keratin. Biometrische Daten für Prävention und personalisierte Therapie.",
    "work.mjP": "MamaJoy — Mobile-first-Marktplatz für Schwangere und junge Mütter in Deutschland. Ruhiges UX, Bestellung in 30 Sekunden.",
    "work.kfP": "Eine digitale Ökosystem-Fläche für Köln: Suche und Buchung von Vereinen, Schulen, Kursen. Mehrsprachig, zentrale Buchung.",
    "ops.display": "Modernes Design Ops — alles auf der Karte.",
    "ops.side": "Werkzeuge für komplexe Multi-Plattform-Produkte — vom Interview bis zum Produktionscode.",
    "ops.c1": "Kern-Disziplinen",
    "ops.c2": "Tools & Technologie",
    "ops.c3": "Methoden",
    "ops.l1": "Interaction Design",
    "ops.l2": "Verhaltens-UX-Audit",
    "ops.l3": "Skalierbare Designsysteme",
    "ops.l4": "Informationsarchitektur",
    "ops.l5": "Schnelles Prototyping in Framer",
    "ops.l6": "Nutzerforschung und Audit",
    "ops.t1": "Figma Enterprise",
    "ops.t2": "React / Next.js",
    "ops.t3": "Framer Motion",
    "ops.t4": "Principle",
    "ops.t5": "Tailwind CSS",
    "ops.t6": "GitHub Ecosystem",
    "ops.m1": "Double Diamond",
    "ops.m2": "Continuous Discovery",
    "ops.m3": "Agile Design Ops",
    "ops.m4": "Section 508 / WCAG",
    "ops.m5": "Quantitative A/B-Audits",
    "proc.display": "Ein systematischer Produktprozess.",
    "proc.side": "Von unklaren Problemen zu produktionsreifen Design-Frameworks.",
    "proc.1t": "Discover und Scope",
    "proc.1p": "Produktprobleme über Interviews und Business-Metriken kartieren.",
    "proc.2t": "Interaktive Frameworks",
    "proc.2p": "Verhaltens-Wireframes für Navigation und Systemregeln iterieren.",
    "proc.3t": "Polierte Visuals",
    "proc.3p": "Visuelles Design mit Microcopy und skalierbaren Tokens.",
    "proc.4t": "Handoff und Governance",
    "proc.4p": "Dev-Specs und laufende Verhaltensaudits.",
    "quotes.display": "Was Kund:innen sagen über ",
    "quotes.side": "Enge Arbeit mit wachsenden Firmen und Corporate-Teams — messbarer Produktfortschritt.",
    "quotes.q": "„Tetiana hat unser Web-Interface für biometrische Daten grundlegend verändert. Mit ihrer UX/UI- und Front-end-Führung bekam das Startup sauberen, responsiven Code und ein skalierbares Figma-System — Sprints wurden schneller, Agile blieb. Eine Systemdenkerin.“",
    "quotes.role": "Chief Executive Officer · Industrial Biotechnologist Entrepreneur",
    "cta.kicker": "Lassen Sie uns zusammenarbeiten",
    "cta.display": "Haben Sie ein ambitioniertes<br>Projekt?",
    "cta.lede": "Ich nehme neue System- und Visual-Design-Projekte an. Komplexe Tools, Health-Plattformen, Fintech — lassen Sie uns eine systemische Antwort bauen.",
    "cta.alt": "Warmer Sandsteinbogen",
    "foot.copy": "© 2025 Tetiana Zaichenko. Alle Rechte vorbehalten.",
    "case.badge": "UX/UI Case Study",
    "case.role": "Rolle",
    "case.time": "Zeitraum",
    "case.tools": "Tools",
    "case.plat": "Plattform",
    "case.roleVal": "Lead UX/UI Designer",
    "case.about": "Über das Projekt",
    "case.pain": "Problem und Nutzer-Pains",
    "case.research": "Tiefenrecherche",
    "case.personas": "Personas",
    "case.flow": "User Flow",
    "case.lofi": "Low-fi-Prototypen und Iterationen",
    "case.id": "Identität und visuelle Sprache",
    "case.ui": "Finales UI-Design",
    "case.ix": "Interaktion",
    "case.insights": "Zentrale Insights",
    "case.st": "Status:",
    "case.go": "Ziele:",
    "case.pa": "Pains:",
    "case.be": "Verhalten:",
    "case.path": "Pfad:",
    "case.colors": "Farbe",
    "case.comps": "Interface-Komponenten",
    "case.tested": "✓ Durch Nutzertests bestätigt",
    "case.iter1": "Iteration 1",
    "case.iter2": "Iteration 2",
    "case.iter3": "Iteration 3",
    "case.statInt": "Tiefeninterviews",
    "case.statSurvey": "Antworten in der Online-Umfrage",
    "case.statComp": "Zentrale Wettbewerber",
    "case.compH": "Wettbewerbsanalyse",
    "mj.h": "MamaJoy — ein mobiler Shop für Mütter und Babys bis 2 Jahre.",
    "mj.lede": "Ein intuitiver Service für Schwangere und Eltern von Kindern unter zwei: weniger kognitive Last, Fürsorge im Alltag.",
    "mj.timeVal": "3 Monate (2025)",
    "mj.toolsVal": "Figma, FigJam / Miro, VS Code",
    "mj.platVal": "iOS & Android",
    "kf.h": "Klubfinder — ein digitales Ökosystem für die akademische Community",
    "kf.lede": "Web-Ressource für Kölner Schulen und Clubs. Klare Architektur für Bewerber, Schüler und Lehrkräfte.",
    "kf.timeVal": "1 Monat (2025)",
    "kf.platVal": "Web / Desktop & Mobile",
    "mic.h": "MicBioMate — Plattform für die Biosynthese intakten Keratins",
    "mic.lede": "Corporate-Site eines Biotech-Start-ups: Wissenschaft, Technologie und Partnerbereiche.",
    "mic.timeVal": "1,5 Monate (2026)",
    "mic.toolsVal": "Figma, FigJam / Miro, VS Code, Python",
    "mic.platVal": "Web / Desktop & Mobile",
  };

  const fr = {
    "nav.status": "Available for Q3",
    "nav.home": "Accueil",
    "nav.product": "Produit",
    "nav.tech": "Technologies",
    "nav.app": "Application",
    "nav.work": "Travaux",
    "nav.about": "À propos",
    "nav.services": "Services",
    "nav.process": "Processus",
    "nav.reviews": "Avis",
    "nav.cta": "Parlons-en",
    "nav.contact": "Contact",
    "nav.menu": "Ouvrir le menu",
    "nav.menuClose": "Fermer le menu",
    "nav.aria": "Navigation principale",
    "nav.lang": "Langue",
    "nav.homeBack": "← Accueil",
    "nav.prevCase": "Étude précédente",
    "nav.nextCase": "Étude suivante",
    "cursor.case": "Cas",
    "hero.kicker": "designeuse d’interfaces",
    "hero.display": "Créer des expériences numériques justes.",
    "hero.lede": "Je résous des problèmes produit complexes par la recherche utilisateur et un design sobre. Des systèmes qui lient les gens et la technologie.",
    "hero.ctaCases": "Voir une sélection",
    "hero.ctaStory": "Lire mon histoire",
    "hero.alt": "Langage visuel du portfolio — moodboard sable chaud",
    "about.display": "La forme suit le ressenti, pensée pour l’échelle.",
    "about.side": "Relier des objectifs business stricts à une interaction humaine, souple et organique.",
    "about.h3": "Un design retenu, qui soulage les flux de travail.",
    "about.p1": "Je conçois des interfaces claires : les problèmes techniques deviennent un UI/UX intuitif. Un bon design system est une plateforme pour l’équipe, pas seulement une doc visuelle.",
    "about.p2": "Ma pratique tient aux tests utilisateurs et à une typographie nette. Moins de structure superflue, plus de clarté.",
    "about.quoteBy": "Tetiana Zaichenko",
    "svc.display": "Des services sur tout le cycle de vie du produit.",
    "svc.side": "De la validation stratégique à la documentation finale du système.",
    "svc.1t": "Recherche UX",
    "svc.1p": "Ateliers de discovery, entretiens, cartes d’utilisabilité et contrôles de comportement.",
    "svc.2t": "Design d’interface",
    "svc.2p": "Interfaces responsive, précises au pixel, avec des règles de composition strictes.",
    "svc.3t": "Prototypage",
    "svc.3p": "Modèles interactifs des états, transitions et micro-interactions.",
    "svc.4t": "Design systems",
    "svc.4p": "Architecture de composants, tokens et protocoles de handoff.",
    "work.display": "Des cas construits au pixel près.",
    "work.side": "Produits numériques complexes, objectifs clairs, logique d’interaction et frameworks scalables.",
    "tag.ux": "Audit UX",
    "tag.health": "HealthTech",
    "tag.platform": "Plateforme",
    "tag.web": "Application web",
    "tag.ed": "EdTech / GovTech",
    "work.role26": "2026 · Lead design",
    "work.role25": "2025 · Lead design",
    "work.micP": "Suivi biotech et kératine intacte. Données biométriques pour la prévention et une thérapie personnalisée.",
    "work.mjP": "MamaJoy — marketplace mobile-first pour les femmes enceintes et jeunes mères en Allemagne. UX calme, commande en 30 secondes.",
    "work.kfP": "Un écosystème numérique pour Cologne : recherche et inscription aux clubs, écoles et cours. Multilingue, réservation centrale.",
    "ops.display": "Design Ops moderne — tout sur la carte.",
    "ops.side": "Une boîte à outils pour des produits multi-plateformes — de l’entretien au code en production.",
    "ops.c1": "Disciplines clés",
    "ops.c2": "Outils et technologies",
    "ops.c3": "Méthodes",
    "ops.l1": "Design d’interaction",
    "ops.l2": "Audit UX comportemental",
    "ops.l3": "Design systems scalables",
    "ops.l4": "Architecture de l’information",
    "ops.l5": "Prototypage rapide dans Framer",
    "ops.l6": "Recherche utilisateur et audit",
    "ops.t1": "Figma Enterprise",
    "ops.t2": "React / Next.js",
    "ops.t3": "Framer Motion",
    "ops.t4": "Principle",
    "ops.t5": "Tailwind CSS",
    "ops.t6": "GitHub Ecosystem",
    "ops.m1": "Double Diamant",
    "ops.m2": "Discovery continue",
    "ops.m3": "Agile Design Ops",
    "ops.m4": "Section 508 / WCAG",
    "ops.m5": "Audits A/B quantitatifs",
    "proc.display": "Un processus produit systématique.",
    "proc.side": "Des problèmes flous aux frameworks de design prêts pour la production.",
    "proc.1t": "Discovery et cadrage",
    "proc.1p": "Cartographier les problèmes produit via des entretiens et des métriques business.",
    "proc.2t": "Frameworks interactifs",
    "proc.2p": "Itérer des wireframes comportementaux pour la navigation et les règles système.",
    "proc.3t": "Visuels aboutis",
    "proc.3p": "Design visuel, microcopy et tokens scalables.",
    "proc.4t": "Handoff et gouvernance",
    "proc.4p": "Specs dev et audits comportementaux continus.",
    "quotes.display": "Ce que les clients disent de ",
    "quotes.side": "Collaboration étroite avec des entreprises en croissance et des équipes corporate — un progrès produit mesurable.",
    "quotes.q": "« Tetiana a transformé notre interface web de données biométriques. Avec son lead UX/UI et front-end, la startup a reçu un code responsive propre et un système Figma scalable — les sprints ont accéléré, l’Agile a tenu. Une penseuse systémique. »",
    "quotes.role": "Chief Executive Officer · Industrial Biotechnologist Entrepreneur",
    "cta.kicker": "Travaillons ensemble",
    "cta.display": "Vous avez un projet<br>ambitieux ?",
    "cta.lede": "Je prends de nouveaux projets de systèmes et de design visuel. Outils complexes, santé, fintech — construisons une réponse systémique.",
    "cta.alt": "Arche architecturale en grès chaud",
    "foot.copy": "© 2025 Tetiana Zaichenko. Tous droits réservés.",
    "case.badge": "UX/UI Case Study",
    "case.role": "Rôle",
    "case.time": "Durée",
    "case.tools": "Outils",
    "case.plat": "Plateforme",
    "case.roleVal": "Lead UX/UI Designer",
    "case.about": "À propos du projet",
    "case.pain": "Problème et douleurs utilisateurs",
    "case.research": "Recherche approfondie",
    "case.personas": "Personas",
    "case.flow": "Parcours utilisateur",
    "case.lofi": "Prototypes lo-fi et itérations",
    "case.id": "Identité et langage visuel",
    "case.ui": "UI finale",
    "case.ix": "Interaction",
    "case.insights": "Insights clés",
    "case.st": "Statut :",
    "case.go": "Objectifs :",
    "case.pa": "Freins :",
    "case.be": "Comportement :",
    "case.path": "Parcours :",
    "case.colors": "Couleurs",
    "case.comps": "Composants d’interface",
    "case.tested": "✓ Confirmé par des tests utilisateurs",
    "case.iter1": "Itération 1",
    "case.iter2": "Itération 2",
    "case.iter3": "Itération 3",
    "case.statInt": "Entretiens approfondis",
    "case.statSurvey": "Réponses au questionnaire",
    "case.statComp": "Concurrentes clés",
    "case.compH": "Analyse concurrentielle",
    "mj.h": "MamaJoy — une boutique mobile pour les mères et les bébés jusqu’à 2 ans.",
    "mj.lede": "Un service mobile pour les femmes enceintes et les parents d’enfants de moins de deux ans : moins de charge cognitive, du soin dans le quotidien.",
    "mj.timeVal": "3 mois (2025)",
    "mj.toolsVal": "Figma, FigJam / Miro, VS Code",
    "mj.platVal": "iOS & Android",
    "kf.h": "Klubfinder — un écosystème numérique pour la communauté académique",
    "kf.lede": "Ressource web pour les écoles et clubs de Cologne. Architecture claire pour candidats, élèves et enseignant·es.",
    "kf.timeVal": "1 mois (2025)",
    "kf.platVal": "Web / Desktop & Mobile",
    "mic.h": "MicBioMate — plateforme de biosynthèse de kératine intacte",
    "mic.lede": "Site corporate d’une startup biotech : science, technologies et espaces partenaires.",
    "mic.timeVal": "1,5 mois (2026)",
    "mic.toolsVal": "Figma, FigJam / Miro, VS Code, Python",
    "mic.platVal": "Web / Desktop & Mobile",
  };

  const it = {
    "nav.status": "Available for Q3",
    "nav.home": "Home",
    "nav.product": "Prodotto",
    "nav.tech": "Tecnologie",
    "nav.app": "Applicazione",
    "nav.work": "Lavori",
    "nav.about": "Su di me",
    "nav.services": "Servizi",
    "nav.process": "Processo",
    "nav.reviews": "Recensioni",
    "nav.cta": "Parliamone",
    "nav.contact": "Contatto",
    "nav.menu": "Apri il menu",
    "nav.menuClose": "Chiudi il menu",
    "nav.aria": "Navigazione principale",
    "nav.lang": "Lingua",
    "nav.homeBack": "← Home",
    "nav.prevCase": "Case precedente",
    "nav.nextCase": "Case successivo",
    "cursor.case": "Case",
    "hero.kicker": "designer di interfacce",
    "hero.display": "Esperienze digitali con senso.",
    "hero.lede": "Risolvo problemi di prodotto complessi con ricerca utenti e design sobrio. Sistemi che uniscono persone e tecnologia.",
    "hero.ctaCases": "Vedi i selezionati",
    "hero.ctaStory": "Leggi la mia storia",
    "hero.alt": "Linguaggio visivo del portfolio — moodboard sabbia calda",
    "about.display": "La forma segue la sensazione, pensata per scalare.",
    "about.side": "Unire obiettivi di business rigorosi a un’interazione umana, flessibile e organica.",
    "about.h3": "Design contenuto, che alleggerisce i flussi di lavoro.",
    "about.p1": "Progetto interfacce chiare: i problemi tecnici diventano UI/UX intuitiva. Un buon design system è una piattaforma per il team, non solo documentazione visiva.",
    "about.p2": "La pratica poggia su test con gli utenti e tipografia pulita. Meno struttura di troppo, più chiarezza.",
    "about.quoteBy": "Tetiana Zaichenko",
    "svc.display": "Servizi su tutto il ciclo di vita del prodotto.",
    "svc.side": "Dalla validazione della strategia alla documentazione finale del sistema.",
    "svc.1t": "Ricerca UX",
    "svc.1p": "Workshop di discovery, interviste, mappe di usabilità e controlli comportamentali.",
    "svc.2t": "Design dell’interfaccia",
    "svc.2p": "Interfacce responsive, precise al pixel, con regole di layout rigorose.",
    "svc.3t": "Prototipazione",
    "svc.3p": "Modelli interattivi di stati, transizioni e micro-interazioni.",
    "svc.4t": "Design system",
    "svc.4p": "Architettura di componenti, token e protocolli di handoff.",
    "work.display": "Case costruiti al pixel.",
    "work.side": "Prodotti digitali complessi, obiettivi chiari, logica di interazione e framework scalabili.",
    "tag.ux": "Audit UX",
    "tag.health": "HealthTech",
    "tag.platform": "Piattaforma",
    "tag.web": "Web app",
    "tag.ed": "EdTech / GovTech",
    "work.role26": "2026 · Lead design",
    "work.role25": "2025 · Lead design",
    "work.micP": "Monitoraggio biotech e cheratina intatta. Dati biometrici per prevenzione e terapia personalizzata.",
    "work.mjP": "MamaJoy — marketplace mobile-first per donne in gravidanza e neo-mamme in Germania. UX calma, ordine in 30 secondi.",
    "work.kfP": "Un ecosistema digitale per Colonia: ricerca e iscrizione a club, scuole e corsi. Multilingue, prenotazione centrale.",
    "ops.display": "Design Ops moderno — tutto sulla mappa.",
    "ops.side": "Un kit per prodotti multi-piattaforma — dall’intervista al codice in produzione.",
    "ops.c1": "Discipline principali",
    "ops.c2": "Strumenti e tecnologie",
    "ops.c3": "Metodi",
    "ops.l1": "Interaction design",
    "ops.l2": "Audit UX comportamentale",
    "ops.l3": "Design system scalabili",
    "ops.l4": "Architettura dell’informazione",
    "ops.l5": "Prototipazione rapida in Framer",
    "ops.l6": "Ricerca utenti e audit",
    "ops.t1": "Figma Enterprise",
    "ops.t2": "React / Next.js",
    "ops.t3": "Framer Motion",
    "ops.t4": "Principle",
    "ops.t5": "Tailwind CSS",
    "ops.t6": "GitHub Ecosystem",
    "ops.m1": "Double Diamond",
    "ops.m2": "Continuous discovery",
    "ops.m3": "Agile Design Ops",
    "ops.m4": "Section 508 / WCAG",
    "ops.m5": "Audit A/B quantitativi",
    "proc.display": "Un processo di prodotto sistematico.",
    "proc.side": "Da problemi sfumati a framework di design pronti per la produzione.",
    "proc.1t": "Discovery e perimetro",
    "proc.1p": "Mappare i problemi di prodotto con interviste e metriche di business.",
    "proc.2t": "Framework interattivi",
    "proc.2p": "Iterare wireframe comportamentali per navigazione e regole di sistema.",
    "proc.3t": "Visual rifiniti",
    "proc.3p": "Design visivo, microcopy e token scalabili.",
    "proc.4t": "Handoff e governance",
    "proc.4p": "Spec per lo sviluppo e audit comportamentali continui.",
    "quotes.display": "Cosa dicono i clienti di ",
    "quotes.side": "Collaborazione stretta con aziende in crescita e team corporate — progresso di prodotto misurabile.",
    "quotes.q": "«Tetiana ha trasformato la nostra interfaccia web sui dati biometrici. Con la sua guida UX/UI e front-end la startup ha ricevuto codice responsive pulito e un sistema Figma scalabile: gli sprint sono accelerati, l’Agile è rimasto. Una pensatrice di sistemi.»",
    "quotes.role": "Chief Executive Officer · Industrial Biotechnologist Entrepreneur",
    "cta.kicker": "Lavoriamo insieme",
    "cta.display": "Hai un progetto<br>ambizioso?",
    "cta.lede": "Accetto nuovi progetti di sistemi e design visivo. Strumenti complessi, health, fintech — costruiamo una risposta sistemica.",
    "cta.alt": "Arco architettonico in pietra sabbia",
    "foot.copy": "© 2025 Tetiana Zaichenko. Tutti i diritti riservati.",
    "case.badge": "UX/UI Case Study",
    "case.role": "Ruolo",
    "case.time": "Tempi",
    "case.tools": "Strumenti",
    "case.plat": "Piattaforma",
    "case.roleVal": "Lead UX/UI Designer",
    "case.about": "Sul progetto",
    "case.pain": "Problema e pain degli utenti",
    "case.research": "Ricerca approfondita",
    "case.personas": "Persona",
    "case.flow": "User flow",
    "case.lofi": "Prototipi lo-fi e iterazioni",
    "case.id": "Identità e linguaggio visivo",
    "case.ui": "UI finale",
    "case.ix": "Interazione",
    "case.insights": "Insight chiave",
    "case.st": "Stato:",
    "case.go": "Obiettivi:",
    "case.pa": "Dolori:",
    "case.be": "Comportamento:",
    "case.path": "Percorso:",
    "case.colors": "Colore",
    "case.comps": "Componenti UI",
    "case.tested": "✓ Confermato dai test con gli utenti",
    "case.iter1": "Iterazione 1",
    "case.iter2": "Iterazione 2",
    "case.iter3": "Iterazione 3",
    "case.statInt": "Interviste in profondità",
    "case.statSurvey": "Risposte al questionario",
    "case.statComp": "Competitor chiave",
    "case.compH": "Analisi competitiva",
    "mj.h": "MamaJoy — shop mobile per mamme e bambini fino a 2 anni.",
    "mj.lede": "Un servizio mobile per donne in gravidanza e genitori di bambini sotto i due anni: meno carico cognitivo, cura nella routine.",
    "mj.timeVal": "3 mesi (2025)",
    "mj.toolsVal": "Figma, FigJam / Miro, VS Code",
    "mj.platVal": "iOS & Android",
    "kf.h": "Klubfinder — ecosistema digitale per la comunità accademica",
    "kf.lede": "Risorsa web per scuole e club di Colonia. Architettura chiara per candidati, studenti e docenti.",
    "kf.timeVal": "1 mese (2025)",
    "kf.platVal": "Web / Desktop & Mobile",
    "mic.h": "MicBioMate — piattaforma per la biosintesi di cheratina intatta",
    "mic.lede": "Sito corporate di una startup biotech: scienza, tecnologie e aree partner.",
    "mic.timeVal": "1,5 mesi (2026)",
    "mic.toolsVal": "Figma, FigJam / Miro, VS Code, Python",
    "mic.platVal": "Web / Desktop & Mobile",
  };

  const pl = {
    "nav.status": "Available for Q3",
    "nav.home": "Start",
    "nav.product": "Produkt",
    "nav.tech": "Technologie",
    "nav.app": "Aplikacja",
    "nav.work": "Prace",
    "nav.about": "O mnie",
    "nav.services": "Usługi",
    "nav.process": "Proces",
    "nav.reviews": "Opinie",
    "nav.cta": "Porozmawiajmy",
    "nav.contact": "Kontakt",
    "nav.menu": "Otwórz menu",
    "nav.menuClose": "Zamknij menu",
    "nav.aria": "Nawigacja główna",
    "nav.lang": "Język",
    "nav.homeBack": "← Strona główna",
    "nav.prevCase": "Poprzedni case",
    "nav.nextCase": "Następny case",
    "cursor.case": "Case",
    "hero.kicker": "projektantka interfejsów",
    "hero.display": "Tworzenie sensownych doświadczeń cyfrowych.",
    "hero.lede": "Rozwiązuję złożone problemy produktowe przez research użytkowników i oszczędny design. Systemy, które łączą ludzi i technologię.",
    "hero.ctaCases": "Zobacz wybrane",
    "hero.ctaStory": "Przeczytaj moją historię",
    "hero.alt": "Język wizualny portfolio — ciepły, piaskowy moodboard",
    "about.display": "Forma idzie za odczuciem i jest zbudowana na skalę.",
    "about.side": "Łączę twarde cele biznesowe z żywą, ludzką interakcją.",
    "about.h3": "Powściągliwy design, który odciąża procesy.",
    "about.p1": "Tworzę czytelne interfejsy: problemy techniczne stają się intuicyjnym UI/UX. Dobry design system to platforma dla zespołu, nie tylko dokumentacja wizualna.",
    "about.p2": "Praktyka opiera się na testach z użytkownikami i czystej typografii. Mniej zbędnej struktury — więcej jasności.",
    "about.quoteBy": "Tetiana Zaichenko",
    "svc.display": "Usługi na cały cykl życia produktu.",
    "svc.side": "Od walidacji strategii po końcową dokumentację systemu.",
    "svc.1t": "Research UX",
    "svc.1p": "Warsztaty discovery, wywiady, mapy użyteczności i sprawdzenie zachowań.",
    "svc.2t": "Projekt interfejsu",
    "svc.2p": "Responsywne interfejsy dopracowane do piksela, ze ścisłymi regułami układu.",
    "svc.3t": "Prototypowanie",
    "svc.3p": "Interaktywne modele stanów, przejść i mikrointerakcji.",
    "svc.4t": "Design systemy",
    "svc.4p": "Skalowalna architektura komponentów, tokeny i protokoły przekazania.",
    "work.display": "Case’y złożone z precyzją do piksela.",
    "work.side": "Złożone produkty cyfrowe, jasne cele, logika interakcji i skalowalne frameworki.",
    "tag.ux": "Audyt UX",
    "tag.health": "HealthTech",
    "tag.platform": "Platforma",
    "tag.web": "Aplikacja web",
    "tag.ed": "EdTech / GovTech",
    "work.role26": "2026 · Lead designu",
    "work.role25": "2025 · Lead designu",
    "work.micP": "Monitoring biotech i nienaruszona keratyna. Dane biometryczne do profilaktyki i spersonalizowanej terapii.",
    "work.mjP": "MamaJoy — marketplace mobile-first dla kobiet w ciąży i młodych mam w Niemczech. Spokojny UX, zamówienie w 30 sekund.",
    "work.kfP": "Jedna cyfrowa ekosystemowa przestrzeń dla Kolonii: wyszukiwanie i zapisy do klubów, szkół i zajęć. Wielojęzyczność, centralna rezerwacja.",
    "ops.display": "Nowoczesne Design Ops — wszystko na mapie.",
    "ops.side": "Zestaw narzędzi do złożonych produktów wieloplatformowych — od wywiadu do kodu w produkcji.",
    "ops.c1": "Główne dyscypliny",
    "ops.c2": "Narzędzia i technologie",
    "ops.c3": "Metody",
    "ops.l1": "Projektowanie interakcji",
    "ops.l2": "Audyt UX zachowań",
    "ops.l3": "Skalowalne design systemy",
    "ops.l4": "Architektura informacji",
    "ops.l5": "Szybkie prototypowanie we Framer",
    "ops.l6": "Research użytkowników i audyt",
    "ops.t1": "Figma Enterprise",
    "ops.t2": "React / Next.js",
    "ops.t3": "Framer Motion",
    "ops.t4": "Principle",
    "ops.t5": "Tailwind CSS",
    "ops.t6": "GitHub Ecosystem",
    "ops.m1": "Double Diamond",
    "ops.m2": "Continuous discovery",
    "ops.m3": "Agile Design Ops",
    "ops.m4": "Section 508 / WCAG",
    "ops.m5": "Ilościowe audyty A/B",
    "proc.display": "Systematyczny proces produktu.",
    "proc.side": "Od niejasnego problemu do frameworków designu gotowych na produkcję.",
    "proc.1t": "Odkrycie i zakres",
    "proc.1p": "Mapuję problemy produktu przez wywiady i metryki biznesowe.",
    "proc.2t": "Interaktywne frameworki",
    "proc.2p": "Iteracje behawioralnych wireframe’ów nawigacji i zasad systemu.",
    "proc.3t": "Dopracowany wizual",
    "proc.3p": "Design wizualny, mikrocopy i skalowalne tokeny.",
    "proc.4t": "Przekazanie i zarządzanie",
    "proc.4p": "Specyfikacje dla developmentu i bieżący audyt zachowań.",
    "quotes.display": "Co klienci mówią o ",
    "quotes.side": "Ścisła współpraca z rosnącymi firmami i zespołami korporacyjnymi — mierzalny postęp produktu.",
    "quotes.q": "„Tetiana całkowicie zmieniła nasz interfejs webowy do danych biometrycznych. Dzięki jej prowadzeniu UX/UI i front-endu startup dostał czysty, responsywny kod i skalowalny system w Figma — sprinty przyspieszyły, Agile został. Myślenie systemowe.”",
    "quotes.role": "Chief Executive Officer · Industrial Biotechnologist Entrepreneur",
    "cta.kicker": "Pracujmy razem",
    "cta.display": "Masz ambitny<br>projekt?",
    "cta.lede": "Biorę nowe projekty systemów i designu wizualnego. Złożone narzędzia, zdrowie, fintech — złóżmy systemową odpowiedź.",
    "cta.alt": "Ciepły łuk z piaskowca",
    "foot.copy": "© 2025 Tetiana Zaichenko. Wszelkie prawa zastrzeżone.",
    "case.badge": "UX/UI Case Study",
    "case.role": "Rola",
    "case.time": "Czas",
    "case.tools": "Narzędzia",
    "case.plat": "Platforma",
    "case.roleVal": "Lead UX/UI Designer",
    "case.about": "O projekcie",
    "case.pain": "Problem i bóle użytkowników",
    "case.research": "Pogłębiony research",
    "case.personas": "Persony",
    "case.flow": "Ścieżka użytkownika",
    "case.lofi": "Prototypy lo-fi i iteracje",
    "case.id": "Identyfikacja i język wizualny",
    "case.ui": "Finalny UI",
    "case.ix": "Interakcja",
    "case.insights": "Kluczowe wnioski",
    "case.st": "Status:",
    "case.go": "Cele:",
    "case.pa": "Bóle:",
    "case.be": "Zachowanie:",
    "case.path": "Ścieżka:",
    "case.colors": "Kolor",
    "case.comps": "Komponenty interfejsu",
    "case.tested": "✓ Potwierdzone testami z użytkownikami",
    "case.iter1": "Iteracja 1",
    "case.iter2": "Iteracja 2",
    "case.iter3": "Iteracja 3",
    "case.statInt": "Pogłębionych wywiadów",
    "case.statSurvey": "Odpowiedzi w ankiecie",
    "case.statComp": "Kluczowych konkurentów",
    "case.compH": "Analiza konkurencji",
    "mj.h": "MamaJoy — sklep mobilny dla mam i dzieci do 2 lat.",
    "mj.lede": "Intuicyjny serwis dla kobiet w ciąży i rodziców dzieci do dwóch lat: mniej obciążenia poznawczego, troska w codziennej rutynie.",
    "mj.timeVal": "3 miesiące (2025)",
    "mj.toolsVal": "Figma, FigJam / Miro, VS Code",
    "mj.platVal": "iOS & Android",
    "kf.h": "Klubfinder — cyfrowy ekosystem dla społeczności akademickiej",
    "kf.lede": "Serwis dla szkół i klubów Kolonii. Czytelna architektura dla kandydatów, uczniów i nauczycieli.",
    "kf.timeVal": "1 miesiąc (2025)",
    "kf.platVal": "Web / Desktop & Mobile",
    "mic.h": "MicBioMate — platforma biosyntezy nienaruszonej keratyny",
    "mic.lede": "Strona korporacyjna startupu biotech: nauka, technologie i strefy partnerskie.",
    "mic.timeVal": "1,5 miesiąca (2026)",
    "mic.toolsVal": "Figma, FigJam / Miro, VS Code, Python",
    "mic.platVal": "Web / Desktop & Mobile",
  };

  if (window.TA_I18N && window.TA_I18N.extend) {
    window.TA_I18N.extend({ ru, en, uk, de, fr, it, pl });
  }
})();
